default_language_version:
    python: python3.11
repos:
  # https://github.com/astral-sh/ruff-pre-commit#using-ruff-with-pre-commit
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.280
    hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix, --exclude, alembic]

  - repo: https://github.com/psf/black
    # https://black.readthedocs.io/en/stable/integrations/source_version_control.html
    rev: 23.7.0
    hooks:
      - id: black
        args: [--safe, --exclude, alembic]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    # https://github.com/pre-commit/pre-commit-hooks#using-pre-commit-hooks-with-pre-commit
    rev: v4.4.0
    hooks:
        # https://github.com/pre-commit/pre-commit-hooks
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args:
        - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: mixed-line-ending
        # please work
        args:
          - --fix=lf
